services:
  backend:
    networks:
      default:
      easypanel:
        aliases:
          - dismal-api

  web:
    environment:
      BASE_API_URL: http://dismal-api:8080
      NEXT_PUBLIC_BASE_API_URL: http://dismal-api:8080
    networks:
      default:
      easypanel:
        aliases:
          - dismal-admin

networks:
  easypanel:
    external: true
    name: ${EASYPANEL_PROXY_NETWORK:-easypanel}
