ALTER TABLE IF EXISTS integration_settings
    ADD COLUMN IF NOT EXISTS smtp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS smtp_host VARCHAR(255),
    ADD COLUMN IF NOT EXISTS smtp_port INTEGER,
    ADD COLUMN IF NOT EXISTS smtp_user VARCHAR(255),
    ADD COLUMN IF NOT EXISTS smtp_password TEXT,
    ADD COLUMN IF NOT EXISTS smtp_tls BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS smtp_from_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS smtp_from_name VARCHAR(255);
